version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      # Copier les valeurs depuis .env.local
      - DATABASE_URL=${DATABASE_URL}
      - DATABASE_URL_UNPOOLED=${DATABASE_URL_UNPOOLED}
      - BETTER_AUTH_SECRET=${BETTER_AUTH_SECRET}
      - BETTER_AUTH_URL=${BETTER_AUTH_URL}
      - GROQ_API_KEY=${GROQ_API_KEY}
      - NEXT_PUBLIC_APP_URL=${NEXT_PUBLIC_APP_URL}
    restart: unless-stopped
